export { default as Bible } from './Bible'
export { default as TN } from './TN'
export { default as OBSTN } from './OBSTN'
export { default as TWL } from './TWL'
export { default as TQ } from './TQ'
export { default as Info } from './Info'
