module.exports = {
  content: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        'th-primary': 'var(--primary)',
        'th-secondary': 'var(--secondary)',
        'th-primary-background': 'var(--primary-background)',
        'th-primary-hover-background': 'var(--primary-hover-background)',
        'th-secondary-background': 'var(--secondary-background)',
        'th-tertiary-background': 'var(--tertiary-background)',
        'th-primary-icons': 'var(--primary-icons)',
        'th-secondary-icons': 'var(--secondary-icons)',
        'th-primary-text': 'var(--primary-text)',
        'th-secondary-text': 'var(--secondary-text)',
        'th-disabled-text': 'var(--disabled-text)',
        'th-active-tab-text': 'var(--active-tab-text)',
        'th-primary-link': 'var(--primary-link)',
        'th-hover-primary-link': 'var(--hover-primary-link)',
        'th-disabled-link': 'var(--disabled-link)',
        'th-primary-border': 'var(--primary-border)',
        'th-secondary-border': 'var(--secondary-border)',
        'th-primary-modal-from': 'var(--primary-modal-from)',
        'th-primary-modal-to': 'var(--primary-modal-to)',
        'th-primary-btn-background': 'var(--primary-btn-background)',
        'th-primary-btn-hover': 'var(--primary-btn-hover)',
        'th-active-tab-from': 'var(--active-tab-from)',
        'th-active-tab-to': 'var(--active-tab-to)',
        'th-primary-blur-background': 'var(--primary-blur-background)',
        'th-tertiary-btn-background': 'var(--tertiary-btn-background)',
        'th-tertiary-btn-hover': 'var(--tertiary-btn-hover)',
        'th-quaternary-btn-background': 'var(--quaternary-btn-background)',
        'th-quaternary-btn-hover': 'var(--quaternary-btn-hover)',
        'th-primary-scroll': 'var(--primary-scroll)',
        'th-first-check': 'var(--first-check)',
        'th-second-check': 'var(--second-check)',
        'th-third-check': 'var(--third-check)',
        'th-hover-chapter-from': 'var(--hover-chapter-from)',
        'th-hover-chapter-to': 'var(--hover-chapter-to)',
        'th-primary-switch': 'var(--primary-switch)',
        'th-invalid': 'var(--invalid)',
        'th-input': 'var(--input)',
        'th-input-focus': 'var(--input-focus)',

        'th-divide-verse1': 'var(--divide-verse1)',
        'th-divide-verse2': 'var(--divide-verse2)',
        'th-divide-verse3': 'var(--divide-verse3)',
        'th-divide-verse4': 'var(--divide-verse4)',
        'th-divide-verse5': 'var(--divide-verse5)',
        'th-divide-verse6': 'var(--divide-verse6)',
        'th-divide-verse7': 'var(--divide-verse7)',
        'th-divide-verse8': 'var(--divide-verse8)',
        'th-divide-verse9': 'var(--divide-verse9)',

        gray: {
          150: '#EDEDED',
          250: '#E3E3E3',
          350: '#bcbcbc',
          450: '#AEAEAE',
        },
        teal: {
          350: '#bdcccd',
          650: '#247176',
        },
        cyan: {
          950: '#23585B',
        },
        slate: {
          540: '#519498',
          550: '#3C6E71',
          560: '#1E5053',
          570: '#275356',
          580: '#609295',
        },
        blue: {
          150: '#DCE4E9',
          250: '#B7C9E5',
          350: '#AECCDF',
          450: '#0EA5E9',
        },
      },
    },
  },
  variants: {
    extend: {
      display: ['group-hover'],
    },
  },
  plugins: [require('@tailwindcss/aspect-ratio')],
}
