module.exports = {
  content: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        'th-primary': 'var(--primary)',
        'th-secondary': 'var(--secondary)',
        'th-background-secondary': 'var(--background-secondary)',
        'th-background-tertiary': 'var(--background-tertiary)',
        'th-background-primary': 'var(--background-primary)',
        'th-background-hover': 'var(--background-hover)',
        'th-icons-primary': 'var(--icons-primary)',
        'th-icons-secondary': 'var(--icons-secondary)',
        'th-text-primary': 'var(--text-primary)',
        'th-text-secondary': 'var(--text-secondary)',
        'th-text-disabled': 'var(--text-disabled)',
        'th-link': 'var(--link)',
        'th-link-hover': 'var(--link-hover)',
        'th-border-primary': 'var(--border-primary)',
        'th-border-secondary': 'var(--border-secondary)',
        'th-modal-from': 'var(--modal-from)',
        'th-modal-to': 'var(--modal-to)',
        'th-btn-background-primary': 'var(--btn-background-primary)',
        'th-btn-background-secondary': 'var(--btn-background-secondary)',
        'th-btn-background-tertiary': 'var(--btn-background-tertiary)',
        'th-btn-background-quaternary': 'var(--btn-background-quaternary)',
        'th-active-tab-from': 'var(--active-tab-from)',
        'th-active-tab-to': 'var(--active-tab-to)',
        'th-blur-background': 'var(--blur-background)',

        'th-scroll': 'var(--scroll)',
        'th-first-check': 'var(--first-check)',
        'th-second-check': 'var(--second-check)',
        'th-third-check': 'var(--third-check)',
        'th-hover-chapter-from': 'var(--hover-chapter-from)',
        'th-hover-chapter-to': 'var(--hover-chapter-to)',
        'th-primary-switch': 'var(--primary-switch)',
        'th-invalid': 'var(--invalid)',
        'th-input': 'var(--input)',
        'th-input-focus': 'var(--input-focus)',
        'th-divide-verse1': 'var(--divide-verse1)',
        'th-divide-verse2': 'var(--divide-verse2)',
        'th-divide-verse3': 'var(--divide-verse3)',
        'th-divide-verse4': 'var(--divide-verse4)',
        'th-divide-verse5': 'var(--divide-verse5)',
        'th-divide-verse6': 'var(--divide-verse6)',
        'th-divide-verse7': 'var(--divide-verse7)',
        'th-divide-verse8': 'var(--divide-verse8)',
        'th-divide-verse9': 'var(--divide-verse9)',

        gray: {
          150: '#EDEDED',
          250: '#E3E3E3',
          350: '#bcbcbc',
          450: '#AEAEAE',
        },
        teal: {
          350: '#bdcccd',
          650: '#247176',
        },
        cyan: {
          950: '#23585B',
        },
        slate: {
          540: '#519498',
          550: '#3C6E71',
          560: '#1E5053',
          570: '#275356',
          580: '#609295',
        },
        blue: {
          150: '#DCE4E9',
          250: '#B7C9E5',
          350: '#AECCDF',
          450: '#0EA5E9',
        },
      },
    },
  },
  variants: {
    extend: {
      display: ['group-hover'],
    },
  },
  plugins: [require('@tailwindcss/aspect-ratio')],
}
