module.exports = {
  content: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        'th-primary': 'var(--primary)',
        'th-secondary': 'var(--secondary)',
        'th-primary-background': 'var(--primary-background)',
        'th-primary-hover-background': 'var(--primary-hover-background)',
        'th-secondary-background': 'var(--secondary-background)',
        'th-tertiary-background': 'var(--tertiary-background)',
        'th-primary-icons': 'var(--primary-icons)',
        'th-secondary-icons': 'var(--secondary-icons)',
        'th-primary-text': 'var(--primary-text)',
        'th-secondary-text': 'var(--secondary-text)',
        'th-disabled-text': 'var(--disabled-text)',
        'th-active-tab-text': 'var(--active-tab-text)',
        'th-primary-link': 'var(--primary-link)',
        'th-hover-primary-link': 'var(--hover-primary-link)',
        'th-disabled-link': 'var(--disabled-link)',
        'th-primary-border': 'var(--primary-border)',
        'th-secondary-border': 'var(--secondary-border)',
        'th-primary-modal-from': 'var(--primary-modal-from)',
        'th-primary-modal-to': 'var(--primary-modal-to)',
        'th-primary-btn-background': 'var(--primary-btn-background)',
        'th-primary-btn-hover': 'var(--primary-btn-hover)',
        'th-active-tab-from': 'var(--active-tab-from)',
        'th-active-tab-to': 'var(--active-tab-to)',
        'th-primary-blur-background': 'var(--primary-blur-background)',
        'th-tertiary-btn-background': 'var(--tertiary-btn-background)',
        'th-tertiary-btn-hover': 'var(--tertiary-btn-hover)',
        'th-quaternary-btn-background': 'var(--tertiary-btn-background)',
        'th-quaternary-btn-hover': 'var(--tertiary-btn-hover)',

        gray: {
          150: '#EDEDED',
          250: '#E3E3E3',
          350: '#bcbcbc',
          450: '#AEAEAE',
        },
        teal: {
          350: '#bdcccd',
        },
        slate: { 550: '#3C6E71', 560: '#1E5053', 570: '#275356' },
        blue: {
          150: '#DCE4E9',
          250: '#B7C9E5',
          350: '#AECCDF',
          450: '#0EA5E9',
        },
      },
    },
  },
  variants: {
    extend: {
      display: ['group-hover'],
    },
  },
  plugins: [require('@tailwindcss/aspect-ratio')],
}
