export { default as Bible } from './Bible'
export { default as TN } from './TN'
export { default as TQ } from './TQ'
export { default as OBS } from './OBS'
export { default as OBSTN } from './OBSTN'
export { default as OBSTQ } from './OBSTQ'
export { default as OBSTWL } from './OBSTWL'
export { default as TWL } from './TWL'
