export const steps = {
  1: {
    title: 'Cana.Step1.Title',
    users: 1,
    time: 2400,
    stepGoal: 'Cana.Step1.Goal',
    tools: {},
  },
  2: {
    title: 'Cana.Step2.Title',
    users: 4,
    time: 3000,
    stepGoal: 'Cana.Step2.Goal',
    tools: {},
  },
  3: {
    title: 'Cana.Step3.Title',
    users: 2,
    time: 1200,
    stepGoal: 'Cana.Step3.Goal',
    tools: {},
  },
  4: {
    title: 'Cana.Step4.Title',
    users: 1,
    time: 1200,
    stepGoal: 'Cana.Step4.Goal',
    tools: {},
  },
  5: {
    title: 'Cana.Step5.Title',
    users: 1,
    time: 1800,
    stepGoal: 'Cana.Step5.Goal',
    tools: {},
  },
  6: {
    title: 'Cana.Step6.Title',
    users: 2,
    time: 2400,
    stepGoal: 'Cana.Step6.Goal',
    tools: {},
  },
  7: {
    title: 'Cana.Step7.Title',
    users: 4,
    time: 3600,
    stepGoal: 'Cana.Step7.Goal',
    tools: {},
  },
}
