import { supabase } from 'utils/supabaseClient'

export default async function languageProjectsHandler(req, res) {
  if (!req.headers.token) {
    res.status(401).json({ error: 'Access denied!' })
  }
  supabase.auth.setAuth(req.headers.token)

  const {
    body: { language_id, method_id, code, title, resources, steps },
    method,
  } = req

  switch (method) {
    case 'POST':
      try {
        // вот тут мы делаем валидацию и записываем в 2 таблицы. Какие входные данные - можно самому придумать. Или принять все поля формы, или json просто валидировать
        const { data: current_method, error: methodError } = await supabase
          .from('methods')
          .select('*')
          .eq('id', method_id)
          .single()
        if (methodError) throw methodError
        /**
         * Сверить что все методы из ресурса пришли с формы. Так же получаем, какой ресурс основной
         * После этого получаем и парсим манифесты и записываем в базу.
         * Выполнить все в одной транзакции, что-то не пройдет надо чтобы ничего не записалось
         * Взять на пока что список шагов как есть, добавить только айди проекта и порядковый номер шага.
         * Но надо не забыть, что потом надо брать от юзера измененные тексты с формы создания проекта.
         * Я просто показываю примерно как все должно быть
         */

        const { data, error } = await supabase.from('projects').insert([
          {
            title,
            code,
            language_id,
            type: current_method.type,
            resources: {
              literal: {
                owner: 'ru_gl',
                repo: 'ru_rlob',
                commit: 'fcfef9689dd6897892dbcced76ba8beb0eacaa62',
                manifest: {
                  dublin_core: {
                    type: 'bundle',
                    conformsto: 'rc0.2',
                    comment: 'RLOB',
                    format: 'text/usfm3',
                    identifier: 'rlob',
                    title: 'Russian Literal Open Bible',
                    subject: 'Aligned Bible',
                    description:
                      'Russian RLOB aligned to unfoldingWord® Greek New Testament',
                    language: {
                      identifier: 'ru',
                      title: 'Русский',
                      direction: 'ltr',
                    },
                    source: [
                      {
                        identifier: 'rlob',
                        language: 'ru',
                        version: '1.0.0',
                      },
                    ],
                    rights: 'CC BY-SA 4.0',
                    creator: 'Door43 World Missions Community',
                    contributor: ['Door43 World Missions Community'],
                    relation: ['ru/tw', 'el-x-koine/ugnt'],
                    publisher: 'Door43 World Missions Community',
                    issued: '2020-08-12',
                    modified: '2020-08-12',
                    version: '1',
                  },
                  checking: {
                    checking_entity: ['Door43 World Missions Community'],
                    checking_level: '3',
                  },
                  projects: [
                    {
                      title: 'Genesis',
                      versification: 'ufw',
                      identifier: 'gen',
                      sort: 1,
                      path: './01-GEN.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Exodus',
                      versification: 'ufw',
                      identifier: 'exo',
                      sort: 2,
                      path: './02-EXO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Leviticus',
                      versification: 'ufw',
                      identifier: 'lev',
                      sort: 3,
                      path: './03-LEV.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Numbers',
                      versification: 'ufw',
                      identifier: 'num',
                      sort: 4,
                      path: './04-NUM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Deuteronomy',
                      versification: 'ufw',
                      identifier: 'deu',
                      sort: 5,
                      path: './05-DEU.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joshua',
                      versification: 'ufw',
                      identifier: 'jos',
                      sort: 6,
                      path: './06-JOS.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Judges',
                      versification: 'ufw',
                      identifier: 'jdg',
                      sort: 7,
                      path: './07-JDG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Руфь',
                      versification: 'ufw',
                      identifier: 'rut',
                      sort: 8,
                      path: './08-RUT.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Samuel',
                      versification: 'ufw',
                      identifier: '1sa',
                      sort: 9,
                      path: './09-1SA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Samuel',
                      versification: 'ufw',
                      identifier: '2sa',
                      sort: 10,
                      path: './10-2SA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Kings',
                      versification: 'ufw',
                      identifier: '1ki',
                      sort: 11,
                      path: './11-1KI.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Kings',
                      versification: 'ufw',
                      identifier: '2ki',
                      sort: 12,
                      path: './12-2KI.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Chronicles',
                      versification: 'ufw',
                      identifier: '1ch',
                      sort: 13,
                      path: './13-1CH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Chronicles',
                      versification: 'ufw',
                      identifier: '2ch',
                      sort: 14,
                      path: './14-2CH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezra',
                      versification: 'ufw',
                      identifier: 'ezr',
                      sort: 15,
                      path: './15-EZR.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nehemiah',
                      versification: 'ufw',
                      identifier: 'neh',
                      sort: 16,
                      path: './16-NEH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Есфирь',
                      versification: 'ufw',
                      identifier: 'est',
                      sort: 17,
                      path: './17-EST.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Job',
                      versification: 'ufw',
                      identifier: 'job',
                      sort: 18,
                      path: './18-JOB.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Psalms',
                      versification: 'ufw',
                      identifier: 'psa',
                      sort: 19,
                      path: './19-PSA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Proverbs',
                      versification: 'ufw',
                      identifier: 'pro',
                      sort: 20,
                      path: './20-PRO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ecclesiastes',
                      versification: 'ufw',
                      identifier: 'ecc',
                      sort: 21,
                      path: './21-ECC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Song of Solomon',
                      versification: 'ufw',
                      identifier: 'sng',
                      sort: 22,
                      path: './22-SNG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Isaiah',
                      versification: 'ufw',
                      identifier: 'isa',
                      sort: 23,
                      path: './23-ISA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Jeremiah',
                      versification: 'ufw',
                      identifier: 'jer',
                      sort: 24,
                      path: './24-JER.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Lamentations',
                      versification: 'ufw',
                      identifier: 'lam',
                      sort: 25,
                      path: './25-LAM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezekiel',
                      versification: 'ufw',
                      identifier: 'ezk',
                      sort: 26,
                      path: './26-EZK.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Daniel',
                      versification: 'ufw',
                      identifier: 'dan',
                      sort: 27,
                      path: './27-DAN.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Hosea',
                      versification: 'ufw',
                      identifier: 'hos',
                      sort: 28,
                      path: './28-HOS.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joel',
                      versification: 'ufw',
                      identifier: 'jol',
                      sort: 29,
                      path: './29-JOL.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Amos',
                      versification: 'ufw',
                      identifier: 'amo',
                      sort: 30,
                      path: './30-AMO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Авдия',
                      versification: 'ufw',
                      identifier: 'oba',
                      sort: 31,
                      path: './31-OBA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ионы',
                      versification: 'ufw',
                      identifier: 'jon',
                      sort: 32,
                      path: './32-JON.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Micah',
                      versification: 'ufw',
                      identifier: 'mic',
                      sort: 33,
                      path: './33-MIC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nahum',
                      versification: 'ufw',
                      identifier: 'nam',
                      sort: 34,
                      path: './34-NAM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Habakkuk',
                      versification: 'ufw',
                      identifier: 'hab',
                      sort: 35,
                      path: './35-HAB.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zephaniah',
                      versification: 'ufw',
                      identifier: 'zep',
                      sort: 36,
                      path: './36-ZEP.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Haggai',
                      versification: 'ufw',
                      identifier: 'hag',
                      sort: 37,
                      path: './37-HAG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zechariah',
                      versification: 'ufw',
                      identifier: 'zec',
                      sort: 38,
                      path: './38-ZEC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Malachi',
                      versification: 'ufw',
                      identifier: 'mal',
                      sort: 39,
                      path: './39-MAL.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Matthew',
                      versification: 'ufw',
                      identifier: 'mat',
                      sort: 40,
                      path: './41-MAT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Mark',
                      versification: 'ufw',
                      identifier: 'mrk',
                      sort: 41,
                      path: './42-MRK.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Luke',
                      versification: 'ufw',
                      identifier: 'luk',
                      sort: 42,
                      path: './43-LUK.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'John',
                      versification: 'ufw',
                      identifier: 'jhn',
                      sort: 43,
                      path: './44-JHN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Acts',
                      versification: 'ufw',
                      identifier: 'act',
                      sort: 44,
                      path: './45-ACT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Romans',
                      versification: 'ufw',
                      identifier: 'rom',
                      sort: 45,
                      path: './46-ROM.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Corinthians',
                      versification: 'ufw',
                      identifier: '1co',
                      sort: 46,
                      path: './47-1CO.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Corinthians',
                      versification: 'ufw',
                      identifier: '2co',
                      sort: 47,
                      path: './48-2CO.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Galatians',
                      versification: 'ufw',
                      identifier: 'gal',
                      sort: 48,
                      path: './49-GAL.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Ephesians',
                      versification: 'ufw',
                      identifier: 'eph',
                      sort: 49,
                      path: './50-EPH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philippians',
                      versification: 'ufw',
                      identifier: 'php',
                      sort: 50,
                      path: './51-PHP.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Colossians',
                      versification: 'ufw',
                      identifier: 'col',
                      sort: 51,
                      path: './52-COL.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Thessalonians',
                      versification: 'ufw',
                      identifier: '1th',
                      sort: 52,
                      path: './53-1TH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Thessalonians',
                      versification: 'ufw',
                      identifier: '2th',
                      sort: 53,
                      path: './54-2TH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Тимофею',
                      versification: 'ufw',
                      identifier: '1ti',
                      sort: 54,
                      path: './55-1TI.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Тимофею',
                      versification: 'ufw',
                      identifier: '2ti',
                      sort: 55,
                      path: './56-2TI.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Титу',
                      versification: 'ufw',
                      identifier: 'tit',
                      sort: 56,
                      path: './57-TIT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philemon',
                      versification: 'ufw',
                      identifier: 'phm',
                      sort: 57,
                      path: './58-PHM.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Hebrews',
                      versification: 'ufw',
                      identifier: 'heb',
                      sort: 58,
                      path: './59-HEB.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'James',
                      versification: 'ufw',
                      identifier: 'jas',
                      sort: 59,
                      path: './60-JAS.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Peter',
                      versification: 'ufw',
                      identifier: '1pe',
                      sort: 60,
                      path: './61-1PE.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Peter',
                      versification: 'ufw',
                      identifier: '2pe',
                      sort: 61,
                      path: './62-2PE.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Иоанна',
                      versification: 'ufw',
                      identifier: '1jn',
                      sort: 62,
                      path: './63-1JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Иоанна',
                      versification: 'ufw',
                      identifier: '2jn',
                      sort: 63,
                      path: './64-2JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '3 Иоанна',
                      versification: 'ufw',
                      identifier: '3jn',
                      sort: 64,
                      path: './65-3JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Jude',
                      versification: 'ufw',
                      identifier: 'jud',
                      sort: 65,
                      path: './66-JUD.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Revelation',
                      versification: 'ufw',
                      identifier: 'rev',
                      sort: 66,
                      path: './67-REV.usfm',
                      categories: ['bible-nt'],
                    },
                  ],
                },
              },
              simplified: {
                owner: 'ru_gl',
                repo: 'ru_rsob',
                commit: '38c10e570082cc615e45628ae7ea3f38d9b67b8c',
                manifest: {
                  dublin_core: {
                    type: 'bundle',
                    conformsto: 'rc0.2',
                    comment: 'RSOB',
                    format: 'text/usfm3',
                    identifier: 'rsob',
                    title: 'Russian Simplified Open Bible',
                    subject: 'Aligned Bible',
                    description:
                      'Russian RSOB aligned to unfoldingWord® Greek New Testament',
                    language: {
                      identifier: 'ru',
                      title: 'Русский',
                      direction: 'ltr',
                    },
                    source: [
                      {
                        identifier: 'rsob',
                        language: 'ru',
                        version: '1.0.0',
                      },
                    ],
                    rights: 'CC BY-SA 4.0',
                    creator: 'Door43 World Missions Community',
                    contributor: ['Door43 World Missions Community'],
                    relation: ['ru/tw', 'el-x-koine/ugnt'],
                    publisher: 'Door43 World Missions Community',
                    issued: '2020-08-12',
                    modified: '2020-08-12',
                    version: '1',
                  },
                  checking: {
                    checking_entity: ['Door43 World Missions Community'],
                    checking_level: '3',
                  },
                  projects: [
                    {
                      title: 'Бытие',
                      versification: 'ufw',
                      identifier: 'gen',
                      sort: 1,
                      path: './01-GEN.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Исход',
                      versification: 'ufw',
                      identifier: 'exo',
                      sort: 2,
                      path: './02-EXO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Leviticus',
                      versification: 'ufw',
                      identifier: 'lev',
                      sort: 3,
                      path: './03-LEV.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Numbers',
                      versification: 'ufw',
                      identifier: 'num',
                      sort: 4,
                      path: './04-NUM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Deuteronomy',
                      versification: 'ufw',
                      identifier: 'deu',
                      sort: 5,
                      path: './05-DEU.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joshua',
                      versification: 'ufw',
                      identifier: 'jos',
                      sort: 6,
                      path: './06-JOS.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Judges',
                      versification: 'ufw',
                      identifier: 'jdg',
                      sort: 7,
                      path: './07-JDG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Руфь',
                      versification: 'ufw',
                      identifier: 'rut',
                      sort: 8,
                      path: './08-RUT.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Samuel',
                      versification: 'ufw',
                      identifier: '1sa',
                      sort: 9,
                      path: './09-1SA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Samuel',
                      versification: 'ufw',
                      identifier: '2sa',
                      sort: 10,
                      path: './10-2SA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Kings',
                      versification: 'ufw',
                      identifier: '1ki',
                      sort: 11,
                      path: './11-1KI.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Kings',
                      versification: 'ufw',
                      identifier: '2ki',
                      sort: 12,
                      path: './12-2KI.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Chronicles',
                      versification: 'ufw',
                      identifier: '1ch',
                      sort: 13,
                      path: './13-1CH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Chronicles',
                      versification: 'ufw',
                      identifier: '2ch',
                      sort: 14,
                      path: './14-2CH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezra',
                      versification: 'ufw',
                      identifier: 'ezr',
                      sort: 15,
                      path: './15-EZR.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nehemiah',
                      versification: 'ufw',
                      identifier: 'neh',
                      sort: 16,
                      path: './16-NEH.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Есфирь',
                      versification: 'ufw',
                      identifier: 'est',
                      sort: 17,
                      path: './17-EST.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Job',
                      versification: 'ufw',
                      identifier: 'job',
                      sort: 18,
                      path: './18-JOB.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Psalms',
                      versification: 'ufw',
                      identifier: 'psa',
                      sort: 19,
                      path: './19-PSA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Proverbs',
                      versification: 'ufw',
                      identifier: 'pro',
                      sort: 20,
                      path: './20-PRO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ecclesiastes',
                      versification: 'ufw',
                      identifier: 'ecc',
                      sort: 21,
                      path: './21-ECC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Song of Solomon',
                      versification: 'ufw',
                      identifier: 'sng',
                      sort: 22,
                      path: './22-SNG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Isaiah',
                      versification: 'ufw',
                      identifier: 'isa',
                      sort: 23,
                      path: './23-ISA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Jeremiah',
                      versification: 'ufw',
                      identifier: 'jer',
                      sort: 24,
                      path: './24-JER.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Lamentations',
                      versification: 'ufw',
                      identifier: 'lam',
                      sort: 25,
                      path: './25-LAM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezekiel',
                      versification: 'ufw',
                      identifier: 'ezk',
                      sort: 26,
                      path: './26-EZK.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Daniel',
                      versification: 'ufw',
                      identifier: 'dan',
                      sort: 27,
                      path: './27-DAN.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Hosea',
                      versification: 'ufw',
                      identifier: 'hos',
                      sort: 28,
                      path: './28-HOS.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joel',
                      versification: 'ufw',
                      identifier: 'jol',
                      sort: 29,
                      path: './29-JOL.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Amos',
                      versification: 'ufw',
                      identifier: 'amo',
                      sort: 30,
                      path: './30-AMO.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Obadiah',
                      versification: 'ufw',
                      identifier: 'oba',
                      sort: 31,
                      path: './31-OBA.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ионы',
                      versification: 'ufw',
                      identifier: 'jon',
                      sort: 32,
                      path: './32-JON.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Micah',
                      versification: 'ufw',
                      identifier: 'mic',
                      sort: 33,
                      path: './33-MIC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nahum',
                      versification: 'ufw',
                      identifier: 'nam',
                      sort: 34,
                      path: './34-NAM.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Habakkuk',
                      versification: 'ufw',
                      identifier: 'hab',
                      sort: 35,
                      path: './35-HAB.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zephaniah',
                      versification: 'ufw',
                      identifier: 'zep',
                      sort: 36,
                      path: './36-ZEP.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Haggai',
                      versification: 'ufw',
                      identifier: 'hag',
                      sort: 37,
                      path: './37-HAG.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zechariah',
                      versification: 'ufw',
                      identifier: 'zec',
                      sort: 38,
                      path: './38-ZEC.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Malachi',
                      versification: 'ufw',
                      identifier: 'mal',
                      sort: 39,
                      path: './39-MAL.usfm',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Matthew',
                      versification: 'ufw',
                      identifier: 'mat',
                      sort: 40,
                      path: './41-MAT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Mark',
                      versification: 'ufw',
                      identifier: 'mrk',
                      sort: 41,
                      path: './42-MRK.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Луки',
                      versification: 'ufw',
                      identifier: 'luk',
                      sort: 42,
                      path: './43-LUK.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'John',
                      versification: 'ufw',
                      identifier: 'jhn',
                      sort: 43,
                      path: './44-JHN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Деяния',
                      versification: 'ufw',
                      identifier: 'act',
                      sort: 44,
                      path: './45-ACT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Romans',
                      versification: 'ufw',
                      identifier: 'rom',
                      sort: 45,
                      path: './46-ROM.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Corinthians',
                      versification: 'ufw',
                      identifier: '1co',
                      sort: 46,
                      path: './47-1CO.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Corinthians',
                      versification: 'ufw',
                      identifier: '2co',
                      sort: 47,
                      path: './48-2CO.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Galatians',
                      versification: 'ufw',
                      identifier: 'gal',
                      sort: 48,
                      path: './49-GAL.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Ефесянам',
                      versification: 'ufw',
                      identifier: 'eph',
                      sort: 49,
                      path: './50-EPH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philippians',
                      versification: 'ufw',
                      identifier: 'php',
                      sort: 50,
                      path: './51-PHP.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Colossians',
                      versification: 'ufw',
                      identifier: 'col',
                      sort: 51,
                      path: './52-COL.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Thessalonians',
                      versification: 'ufw',
                      identifier: '1th',
                      sort: 52,
                      path: './53-1TH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Thessalonians',
                      versification: 'ufw',
                      identifier: '2th',
                      sort: 53,
                      path: './54-2TH.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Тимофею',
                      versification: 'ufw',
                      identifier: '1ti',
                      sort: 54,
                      path: './55-1TI.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Тимофею',
                      versification: 'ufw',
                      identifier: '2ti',
                      sort: 55,
                      path: './56-2TI.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Титу',
                      versification: 'ufw',
                      identifier: 'tit',
                      sort: 56,
                      path: './57-TIT.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philemon',
                      versification: 'ufw',
                      identifier: 'phm',
                      sort: 57,
                      path: './58-PHM.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Hebrews',
                      versification: 'ufw',
                      identifier: 'heb',
                      sort: 58,
                      path: './59-HEB.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'James',
                      versification: 'ufw',
                      identifier: 'jas',
                      sort: 59,
                      path: './60-JAS.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Peter',
                      versification: 'ufw',
                      identifier: '1pe',
                      sort: 60,
                      path: './61-1PE.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Peter',
                      versification: 'ufw',
                      identifier: '2pe',
                      sort: 61,
                      path: './62-2PE.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 John',
                      versification: 'ufw',
                      identifier: '1jn',
                      sort: 62,
                      path: './63-1JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 John',
                      versification: 'ufw',
                      identifier: '2jn',
                      sort: 63,
                      path: './64-2JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '3 Иоанна',
                      versification: 'ufw',
                      identifier: '3jn',
                      sort: 64,
                      path: './65-3JN.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Jude',
                      versification: 'ufw',
                      identifier: 'jud',
                      sort: 65,
                      path: './66-JUD.usfm',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Revelation',
                      versification: 'ufw',
                      identifier: 'rev',
                      sort: 66,
                      path: './67-REV.usfm',
                      categories: ['bible-nt'],
                    },
                  ],
                },
              },
              tn: {
                owner: 'ru_gl',
                repo: 'ru_tn',
                commit: 'cd4216222c098dd1a58e49c0011e6b3220f9ef38',
                manifest: {
                  dublin_core: {
                    conformsto: 'rc0.2',
                    contributor: [
                      'Ivan Pavlii, PhD in World Literature, Baku Slavic University',
                      'Maria Karyakina, PhD, University of Pretoria, MTh in New Testament, University of South Africa',
                      'Aleksey Voskresenskiy, MTh in New Testament, University of Cardiff, Wales',
                      'Yuri Tamurkin, BTh,  St.Petersburg Christian University',
                      'Anna Savitskaya',
                      'Samuel Kim',
                      'Door43 World Missions Community',
                    ],
                    creator: 'Door43, Russian Open Bible',
                    description:
                      'Open-licensed exegetical notes that provide historical, cultural, and linguistic information for translators. It provides translators and checkers with pertinent, just-in-time information to help them make the best possible translation decisions.',
                    format: 'text/tsv',
                    identifier: 'tn',
                    issued: '2021-05-09',
                    language: {
                      identifier: 'ru',
                      title: 'Русский',
                      direction: 'ltr',
                    },
                    modified: '2021-05-09',
                    publisher: 'Door43, Russian Open Bible',
                    relation: [
                      'ru/ult',
                      'ru/ust',
                      'el-x-koine/ugnt?v=0.19',
                      'hbo/uhb?v=2.1.17',
                      'ru/ta',
                      'ru/tw',
                      'ru/tq',
                      'ru/rlb',
                      'ru/rlob',
                      'ru/rob',
                      'ru/rsob',
                      'ru/rsb',
                      'ru/ulb',
                    ],
                    rights: 'CC BY-SA 4.0',
                    source: [
                      {
                        identifier: 'tn',
                        language: 'ru',
                        version: '50.8',
                      },
                    ],
                    subject: 'TSV Translation Notes',
                    title: 'Russian Translation Notes',
                    type: 'help',
                    version: '50.9',
                  },
                  checking: {
                    checking_entity: ['Door43, Russian Open Bible'],
                    checking_level: '3',
                  },
                  projects: [
                    {
                      title: 'Genesis',
                      versification: 'ufw',
                      identifier: 'gen',
                      sort: 1,
                      path: './en_tn_01-GEN.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Exodus',
                      versification: 'ufw',
                      identifier: 'exo',
                      sort: 2,
                      path: './en_tn_02-EXO.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Leviticus',
                      versification: 'ufw',
                      identifier: 'lev',
                      sort: 3,
                      path: './en_tn_03-LEV.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Numbers',
                      versification: 'ufw',
                      identifier: 'num',
                      sort: 4,
                      path: './en_tn_04-NUM.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Deuteronomy',
                      versification: 'ufw',
                      identifier: 'deu',
                      sort: 5,
                      path: './en_tn_05-DEU.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joshua',
                      versification: 'ufw',
                      identifier: 'jos',
                      sort: 6,
                      path: './en_tn_06-JOS.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Judges',
                      versification: 'ufw',
                      identifier: 'jdg',
                      sort: 7,
                      path: './en_tn_07-JDG.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Руфь',
                      versification: 'ufw',
                      identifier: 'rut',
                      sort: 8,
                      path: './en_tn_08-RUT.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Samuel',
                      versification: 'ufw',
                      identifier: '1sa',
                      sort: 9,
                      path: './en_tn_09-1SA.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Samuel',
                      versification: 'ufw',
                      identifier: '2sa',
                      sort: 10,
                      path: './en_tn_10-2SA.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Kings',
                      versification: 'ufw',
                      identifier: '1ki',
                      sort: 11,
                      path: './en_tn_11-1KI.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Kings',
                      versification: 'ufw',
                      identifier: '2ki',
                      sort: 12,
                      path: './en_tn_12-2KI.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '1 Chronicles',
                      versification: 'ufw',
                      identifier: '1ch',
                      sort: 13,
                      path: './en_tn_13-1CH.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: '2 Chronicles',
                      versification: 'ufw',
                      identifier: '2ch',
                      sort: 14,
                      path: './en_tn_14-2CH.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezra',
                      versification: 'ufw',
                      identifier: 'ezr',
                      sort: 15,
                      path: './en_tn_15-EZR.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nehemiah',
                      versification: 'ufw',
                      identifier: 'neh',
                      sort: 16,
                      path: './en_tn_16-NEH.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Есфирь',
                      versification: 'ufw',
                      identifier: 'est',
                      sort: 17,
                      path: './en_tn_17-EST.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Job',
                      versification: 'ufw',
                      identifier: 'job',
                      sort: 18,
                      path: './en_tn_18-JOB.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Psalms',
                      versification: 'ufw',
                      identifier: 'psa',
                      sort: 19,
                      path: './en_tn_19-PSA.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Proverbs',
                      versification: 'ufw',
                      identifier: 'pro',
                      sort: 20,
                      path: './en_tn_20-PRO.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ecclesiastes',
                      versification: 'ufw',
                      identifier: 'ecc',
                      sort: 21,
                      path: './en_tn_21-ECC.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Song of Solomon',
                      versification: 'ufw',
                      identifier: 'sng',
                      sort: 22,
                      path: './en_tn_22-SNG.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Isaiah',
                      versification: 'ufw',
                      identifier: 'isa',
                      sort: 23,
                      path: './en_tn_23-ISA.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Jeremiah',
                      versification: 'ufw',
                      identifier: 'jer',
                      sort: 24,
                      path: './en_tn_24-JER.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Lamentations',
                      versification: 'ufw',
                      identifier: 'lam',
                      sort: 25,
                      path: './en_tn_25-LAM.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ezekiel',
                      versification: 'ufw',
                      identifier: 'ezk',
                      sort: 26,
                      path: './en_tn_26-EZK.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Daniel',
                      versification: 'ufw',
                      identifier: 'dan',
                      sort: 27,
                      path: './en_tn_27-DAN.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Hosea',
                      versification: 'ufw',
                      identifier: 'hos',
                      sort: 28,
                      path: './en_tn_28-HOS.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Joel',
                      versification: 'ufw',
                      identifier: 'jol',
                      sort: 29,
                      path: './en_tn_29-JOL.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Amos',
                      versification: 'ufw',
                      identifier: 'amo',
                      sort: 30,
                      path: './en_tn_30-AMO.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Obadiah',
                      versification: 'ufw',
                      identifier: 'oba',
                      sort: 31,
                      path: './en_tn_31-OBA.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Ионы',
                      versification: 'ufw',
                      identifier: 'jon',
                      sort: 32,
                      path: './en_tn_32-JON.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Micah',
                      versification: 'ufw',
                      identifier: 'mic',
                      sort: 33,
                      path: './en_tn_33-MIC.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Nahum',
                      versification: 'ufw',
                      identifier: 'nam',
                      sort: 34,
                      path: './en_tn_34-NAM.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Habakkuk',
                      versification: 'ufw',
                      identifier: 'hab',
                      sort: 35,
                      path: './en_tn_35-HAB.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zephaniah',
                      versification: 'ufw',
                      identifier: 'zep',
                      sort: 36,
                      path: './en_tn_36-ZEP.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Haggai',
                      versification: 'ufw',
                      identifier: 'hag',
                      sort: 37,
                      path: './en_tn_37-HAG.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Zechariah',
                      versification: 'ufw',
                      identifier: 'zec',
                      sort: 38,
                      path: './en_tn_38-ZEC.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Malachi',
                      versification: 'ufw',
                      identifier: 'mal',
                      sort: 39,
                      path: './en_tn_39-MAL.tsv',
                      categories: ['bible-ot'],
                    },
                    {
                      title: 'Matthew',
                      versification: 'ufw',
                      identifier: 'mat',
                      sort: 40,
                      path: './en_tn_41-MAT.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Mark',
                      versification: 'ufw',
                      identifier: 'mrk',
                      sort: 41,
                      path: './en_tn_42-MRK.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Luke',
                      versification: 'ufw',
                      identifier: 'luk',
                      sort: 42,
                      path: './en_tn_43-LUK.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'John',
                      versification: 'ufw',
                      identifier: 'jhn',
                      sort: 43,
                      path: './en_tn_44-JHN.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Acts',
                      versification: 'ufw',
                      identifier: 'act',
                      sort: 44,
                      path: './en_tn_45-ACT.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Romans',
                      versification: 'ufw',
                      identifier: 'rom',
                      sort: 45,
                      path: './en_tn_46-ROM.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Corinthians',
                      versification: 'ufw',
                      identifier: '1co',
                      sort: 46,
                      path: './en_tn_47-1CO.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Corinthians',
                      versification: 'ufw',
                      identifier: '2co',
                      sort: 47,
                      path: './en_tn_48-2CO.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Galatians',
                      versification: 'ufw',
                      identifier: 'gal',
                      sort: 48,
                      path: './en_tn_49-GAL.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Ephesians',
                      versification: 'ufw',
                      identifier: 'eph',
                      sort: 49,
                      path: './en_tn_50-EPH.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philippians',
                      versification: 'ufw',
                      identifier: 'php',
                      sort: 50,
                      path: './en_tn_51-PHP.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Colossians',
                      versification: 'ufw',
                      identifier: 'col',
                      sort: 51,
                      path: './en_tn_52-COL.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Thessalonians',
                      versification: 'ufw',
                      identifier: '1th',
                      sort: 52,
                      path: './en_tn_53-1TH.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Thessalonians',
                      versification: 'ufw',
                      identifier: '2th',
                      sort: 53,
                      path: './en_tn_54-2TH.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Тимофею',
                      versification: 'ufw',
                      identifier: '1ti',
                      sort: 54,
                      path: './en_tn_55-1TI.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Тимофею',
                      versification: 'ufw',
                      identifier: '2ti',
                      sort: 55,
                      path: './en_tn_56-2TI.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Титу',
                      versification: 'ufw',
                      identifier: 'tit',
                      sort: 56,
                      path: './en_tn_57-TIT.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Philemon',
                      versification: 'ufw',
                      identifier: 'phm',
                      sort: 57,
                      path: './en_tn_58-PHM.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Hebrews',
                      versification: 'ufw',
                      identifier: 'heb',
                      sort: 58,
                      path: './en_tn_59-HEB.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'James',
                      versification: 'ufw',
                      identifier: 'jas',
                      sort: 59,
                      path: './en_tn_60-JAS.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Peter',
                      versification: 'ufw',
                      identifier: '1pe',
                      sort: 60,
                      path: './en_tn_61-1PE.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Peter',
                      versification: 'ufw',
                      identifier: '2pe',
                      sort: 61,
                      path: './en_tn_62-2PE.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '1 Иоанна',
                      versification: 'ufw',
                      identifier: '1jn',
                      sort: 62,
                      path: './en_tn_63-1JN.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '2 Иоанна',
                      versification: 'ufw',
                      identifier: '2jn',
                      sort: 63,
                      path: './en_tn_64-2JN.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: '3 Иоанна',
                      versification: 'ufw',
                      identifier: '3jn',
                      sort: 64,
                      path: './en_tn_65-3JN.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Jude',
                      versification: 'ufw',
                      identifier: 'jud',
                      sort: 65,
                      path: './en_tn_66-JUD.tsv',
                      categories: ['bible-nt'],
                    },
                    {
                      title: 'Revelation',
                      versification: 'ufw',
                      identifier: 'rev',
                      sort: 66,
                      path: './en_tn_67-REV.tsv',
                      categories: ['bible-nt'],
                    },
                  ],
                },
              },
            },
            method: current_method.title,
            base_manifest: {
              resource: 'simplified',
              books: [
                {
                  name: 'gen',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/01-GEN.usfm',
                },
                {
                  name: 'exo',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/02-EXO.usfm',
                },
                {
                  name: 'lev',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/03-LEV.usfm',
                },
                {
                  name: 'num',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/04-NUM.usfm',
                },
                {
                  name: 'deu',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/05-DEU.usfm',
                },
                {
                  name: 'jos',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/06-JOS.usfm',
                },
                {
                  name: 'jdg',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/07-JDG.usfm',
                },
                {
                  name: 'rut',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/08-RUT.usfm',
                },
                {
                  name: '1sa',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/09-1SA.usfm',
                },
                {
                  name: '2sa',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/10-2SA.usfm',
                },
                {
                  name: '1ki',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/11-1KI.usfm',
                },
                {
                  name: '2ki',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/12-2KI.usfm',
                },
                {
                  name: '1ch',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/13-1CH.usfm',
                },
                {
                  name: '2ch',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/14-2CH.usfm',
                },
                {
                  name: 'ezr',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/15-EZR.usfm',
                },
                {
                  name: 'neh',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/16-NEH.usfm',
                },
                {
                  name: 'est',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/17-EST.usfm',
                },
                {
                  name: 'job',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/18-JOB.usfm',
                },
                {
                  name: 'psa',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/19-PSA.usfm',
                },
                {
                  name: 'pro',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/20-PRO.usfm',
                },
                {
                  name: 'ecc',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/21-ECC.usfm',
                },
                {
                  name: 'sng',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/22-SNG.usfm',
                },
                {
                  name: 'isa',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/23-ISA.usfm',
                },
                {
                  name: 'jer',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/24-JER.usfm',
                },
                {
                  name: 'lam',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/25-LAM.usfm',
                },
                {
                  name: 'ezk',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/26-EZK.usfm',
                },
                {
                  name: 'dan',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/27-DAN.usfm',
                },
                {
                  name: 'hos',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/28-HOS.usfm',
                },
                {
                  name: 'jol',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/29-JOL.usfm',
                },
                {
                  name: 'amo',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/30-AMO.usfm',
                },
                {
                  name: 'oba',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/31-OBA.usfm',
                },
                {
                  name: 'jon',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/32-JON.usfm',
                },
                {
                  name: 'mic',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/33-MIC.usfm',
                },
                {
                  name: 'nam',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/34-NAM.usfm',
                },
                {
                  name: 'hab',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/35-HAB.usfm',
                },
                {
                  name: 'zep',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/36-ZEP.usfm',
                },
                {
                  name: 'hag',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/37-HAG.usfm',
                },
                {
                  name: 'zec',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/38-ZEC.usfm',
                },
                {
                  name: 'mal',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/39-MAL.usfm',
                },
                {
                  name: 'mat',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/41-MAT.usfm',
                },
                {
                  name: 'mrk',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/42-MRK.usfm',
                },
                {
                  name: 'luk',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/43-LUK.usfm',
                },
                {
                  name: 'jhn',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/44-JHN.usfm',
                },
                {
                  name: 'act',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/45-ACT.usfm',
                },
                {
                  name: 'rom',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/46-ROM.usfm',
                },
                {
                  name: '1co',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/47-1CO.usfm',
                },
                {
                  name: '2co',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/48-2CO.usfm',
                },
                {
                  name: 'gal',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/49-GAL.usfm',
                },
                {
                  name: 'eph',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/50-EPH.usfm',
                },
                {
                  name: 'php',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/51-PHP.usfm',
                },
                {
                  name: 'col',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/52-COL.usfm',
                },
                {
                  name: '1th',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/53-1TH.usfm',
                },
                {
                  name: '2th',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/54-2TH.usfm',
                },
                {
                  name: '1ti',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/55-1TI.usfm',
                },
                {
                  name: '2ti',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/56-2TI.usfm',
                },
                {
                  name: 'tit',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/57-TIT.usfm',
                },
                {
                  name: 'phm',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/58-PHM.usfm',
                },
                {
                  name: 'heb',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/59-HEB.usfm',
                },
                {
                  name: 'jas',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/60-JAS.usfm',
                },
                {
                  name: '1pe',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/61-1PE.usfm',
                },
                {
                  name: '2pe',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/62-2PE.usfm',
                },
                {
                  name: '1jn',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/63-1JN.usfm',
                },
                {
                  name: '2jn',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/64-2JN.usfm',
                },
                {
                  name: '3jn',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/65-3JN.usfm',
                },
                {
                  name: 'jud',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/66-JUD.usfm',
                },
                {
                  name: 'rev',
                  link: 'ru_gl/ru_rsob/38c10e570082cc615e45628ae7ea3f38d9b67b8c/67-REV.usfm',
                },
              ],
            },
          },
        ])
        if (error) throw error

        current_method.steps.forEach(async (el, index) => {
          await supabase
            .from('steps')
            .insert([{ ...el, order: index + 1, project_id: data[0].id }])
        })
        res.setHeader('Location', `/projects/${data[0].code}`)
        res.status(201).json({})
      } catch (error) {
        res.status(404).json({ error })
        return
      }
      break
    default:
      res.setHeader('Allow', ['POST'])
      res.status(405).end(`Method ${method} Not Allowed`)
  }
}
